import { useEffect, useState } from "react";
import { deleteAdminDomain, deleteAdminGroup, deleteAdminUser, getAdminContacts, getAdminDomains, getAdminGroups, getAdminStats, getAdminUsers, updateAdminUser } from "../api";
import StatCard from "../components/StatCard";

export default function Admin(){
  const [stats,setStats]=useState({}),[users,setUsers]=useState([]),[groups,setGroups]=useState([]),[domains,setDomains]=useState([]),[contacts,setContacts]=useState([]),[message,setMessage]=useState(""),[busyAction,setBusyAction]=useState("");
  async function load(){const [s,u,g,d,c]=await Promise.all([getAdminStats(),getAdminUsers(),getAdminGroups(),getAdminDomains(),getAdminContacts()]);setStats(s.data);setUsers(u.data);setGroups(g.data);setDomains(d.data);setContacts(c.data);}
  useEffect(()=>{load().catch(e=>setMessage(e.response?.data?.message||"Could not load admin data."));},[]);
  async function toggle(u){const key=`user-${u.id}`;if(busyAction)return;setBusyAction(key);try{await updateAdminUser(u.id,!u.is_admin);setMessage(`${u.email} administrator access updated.`);await load();}catch(e){setMessage(e.response?.data?.message||"Could not update user.");}finally{setBusyAction("");}}
  async function delUser(u){if(!confirm(`Delete ${u.email} and their owned data?`))return;const key=`delete-user-${u.id}`;setBusyAction(key);try{await deleteAdminUser(u.id);await load();}catch(e){setMessage(e.response?.data?.message||"Could not delete user.");}finally{setBusyAction("");}}
  async function delGroup(g){if(!confirm(`Delete group ${g.name}?`))return;const key=`delete-group-${g.id}`;setBusyAction(key);try{await deleteAdminGroup(g.id);await load();}catch(e){setMessage(e.response?.data?.message||"Could not delete group.");}finally{setBusyAction("");}}
  async function delDomain(d){if(!confirm(`Delete ${d.url}?`))return;const key=`delete-domain-${d.id}`;setBusyAction(key);try{await deleteAdminDomain(d.id);await load();}catch(e){setMessage(e.response?.data?.message||"Could not delete domain.");}finally{setBusyAction("");}}
  return <div><div className="page-header"><div><span className="eyebrow">Platform control</span><h1>Administrator</h1><p>Manage users, groups and domains across the entire Domain Monitor instance.</p></div></div>{message&&<div className="message panel">{message}</div>}<section className="stats-grid"><StatCard title="Users" value={stats.users??0}/><StatCard title="Groups" value={stats.groups??0}/><StatCard title="Domains" value={stats.domains??0}/><StatCard title="Pending edits" value={stats.pending_requests??0} tone="orange"/></section>
  <section className="panel"><div className="section-title"><h2>Users</h2><span>Administrator access</span></div><div className="table-wrap"><table><thead><tr><th>User</th><th>Email</th><th>Domains</th><th>Owned groups</th><th>Role</th><th>Actions</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.name}</td><td>{u.email}</td><td>{u.domain_count}</td><td>{u.owned_group_count}</td><td>{u.is_admin?<span className="badge ok">Admin</span>:<span className="badge pending">User</span>}</td><td className="actions"><button className="small" onClick={()=>toggle(u)} disabled={Boolean(busyAction) && busyAction !== `user-${u.id}`} aria-busy={busyAction === `user-${u.id}`}>{busyAction === `user-${u.id}` ? "Saving…" : (u.is_admin?"Remove admin":"Make admin")}</button><button className="small danger" onClick={()=>delUser(u)} disabled={Boolean(busyAction)} aria-busy={busyAction === `delete-user-${u.id}`}>{busyAction === `delete-user-${u.id}` ? "Deleting…" : "Delete"}</button></td></tr>)}</tbody></table></div></section>
  <section className="panel"><div className="section-title"><h2>Groups</h2></div><div className="table-wrap"><table><thead><tr><th>Group</th><th>Owner</th><th>Members</th><th>Domains</th><th>Join code</th><th></th></tr></thead><tbody>{groups.map(g=><tr key={g.id}><td>{g.name}</td><td>{g.owner_name}<br/><span className="subtle">{g.owner_email}</span></td><td>{g.member_count}</td><td>{g.domain_count}</td><td><code>{g.join_code}</code></td><td><button className="small danger" onClick={()=>delGroup(g)} disabled={Boolean(busyAction)} aria-busy={busyAction === `delete-group-${g.id}`}>{busyAction === `delete-group-${g.id}` ? "Deleting…" : "Delete"}</button></td></tr>)}</tbody></table></div></section>
  <section className="panel"><div className="section-title"><h2>Domains</h2><span>Latest 1000</span></div><div className="table-wrap"><table><thead><tr><th>Domain</th><th>Status</th><th>Owner</th><th>Group</th><th>Enabled</th><th></th></tr></thead><tbody>{domains.map(d=><tr key={d.id}><td>{d.url}</td><td>{d.status}</td><td>{d.owner_name||"—"}<br/><span className="subtle">{d.owner_email||""}</span></td><td>{d.group_name||"Personal"}</td><td>{d.enabled?"Yes":"No"}</td><td><button className="small danger" onClick={()=>delDomain(d)} disabled={Boolean(busyAction)} aria-busy={busyAction === `delete-domain-${d.id}`}>{busyAction === `delete-domain-${d.id}` ? "Deleting…" : "Delete"}</button></td></tr>)}</tbody></table></div></section>
  <section className="panel"><div className="section-title"><h2>Contact messages</h2><span>{contacts.length} latest message(s)</span></div><div className="contact-admin-list">{contacts.length ? contacts.map((c)=><div className="contact-admin-row" key={c.id}><div><strong>{c.name}</strong> <span className="subtle">{c.email}</span></div><p>{c.concern}</p><small>{new Date(c.created_at).toLocaleString()}</small></div>) : <p className="empty-state">No contact messages yet.</p>}</div></section>
  </div>;
}
