import { useEffect, useState } from "react";
import { createDashboard, deleteDashboard, getDashboardById, getDashboards, getGroups } from "../api";
import StatCard from "../components/StatCard";
import StatusBadge from "../components/StatusBadge";

export default function CustomDashboards(){
  const [dashboards,setDashboards]=useState([]),[groups,setGroups]=useState([]),[name,setName]=useState(""),[groupId,setGroupId]=useState(""),[selected,setSelected]=useState(null),[message,setMessage]=useState("");
  async function load(){const [d,g]=await Promise.all([getDashboards(),getGroups()]);setDashboards(d.data);setGroups(g.data);if(!selected&&d.data.length)loadDashboard(d.data[0].id);}
  async function loadDashboard(id){try{const r=await getDashboardById(id);setSelected(r.data);}catch(e){setMessage(e.response?.data?.message||"Could not load dashboard.");}}
  useEffect(()=>{load().catch(e=>setMessage(e.response?.data?.message||"Could not load dashboards."));},[]);
  async function create(){try{const r=await createDashboard({name,groupId:groupId||null});setName("");setGroupId("");setMessage("Dashboard created.");await load();await loadDashboard(r.data.id);}catch(e){setMessage(e.response?.data?.message||"Could not create dashboard.");}}
  async function remove(id){if(!confirm("Delete this dashboard?"))return;try{await deleteDashboard(id);setSelected(null);await load();}catch(e){setMessage(e.response?.data?.message||"Could not delete dashboard.");}}
  return <div><div className="page-header"><div><span className="eyebrow">Personal workspaces</span><h1>My Dashboards</h1><p>Create persistent views for your personal domains or any groups you belong to.</p></div></div>{message&&<div className="message panel">{message}</div>}<section className="panel dashboard-builder"><h2>Create a dashboard</h2><div className="quick-add"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Dashboard name"/><select value={groupId} onChange={e=>setGroupId(e.target.value)}><option value="">My personal domains only</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name} ({g.permission})</option>)}</select><button onClick={create} disabled={!name.trim()}>Create</button></div></section><div className="dashboard-layout"><section className="panel dashboard-list"><h2>Saved dashboards</h2>{dashboards.map(d=><div className={`dashboard-item ${selected?.dashboard.id===d.id?"selected":""}`} key={d.id}><button onClick={()=>loadDashboard(d.id)}><strong>{d.name}</strong><span>{d.group_name||"Personal"}</span></button><button className="icon-danger" onClick={()=>remove(d.id)}>×</button></div>)}{!dashboards.length&&<p className="empty-state">No custom dashboards yet.</p>}</section>{selected&&<section className="panel"><div className="section-title"><div><h2>{selected.dashboard.name}</h2><span>{selected.dashboard.group_name||"Personal domains"}</span></div></div><section className="stats-grid compact-stats"><StatCard title="Total" value={selected.stats.total}/><StatCard title="OK" value={selected.stats.ok} tone="green"/><StatCard title="Redirects" value={selected.stats.redirects} tone="yellow"/><StatCard title="4xx" value={selected.stats.client_errors} tone="orange"/><StatCard title="5xx" value={selected.stats.server_errors} tone="red"/><StatCard title="Unreachable" value={selected.stats.unreachable} tone="gray"/></section><div className="table-wrap"><table><thead><tr><th>Domain</th><th>Status</th><th>Response</th><th>Last checked</th></tr></thead><tbody>{selected.domains.map(d=><tr key={d.id}><td>{d.url}</td><td><StatusBadge status={d.status} code={d.status_code}/></td><td>{d.response_time_ms??"-"} ms</td><td>{d.last_checked_at?new Date(d.last_checked_at).toLocaleString():"Never"}</td></tr>)}</tbody></table></div></section>}</div></div>;
}
